NEvents             = 30000

executable          = runMinBias.sh
arguments           = $(NEvents) $(ProcId)
output              = batchlog/runMinBias.$(ClusterId).out
error               = batchlog/runMinBias.$(ClusterId).err
log                 = batchlog/runMinBiasSim.$(ClusterId).log
transfer_input_files    = sandbox.tar.bz2
#getenv              = True
request_cpus        = 10


transfer_output_files = ""
+JobFlavour        = "nextweek"
queue 10
