NEvents             = 300000

executable          = runMinBias.sh
arguments           = $(NEvents)
output              = batchlog/runMinBias.$(ClusterId).out
error               = batchlog/runMinBias.$(ClusterId).err
log                 = batchlog/runMinBiasSim.$(ClusterId).log
transfer_input_files    = sandbox.tar.bz2
#getenv              = True
request_cpus        = 12


transfer_output_files = ""
+JobFlavour        = "nextweek"
queue
