PU_parameter        = 100
NEvents             = 50

executable          = runSim.sh
arguments           = $(PU_parameter) $(NEvents) $(ProcId)
output              = batchlog/runSim.$(ClusterId).$(ProcId).out
error               = batchlog/runSim.$(ClusterId).$(ProcId).err
log                 = batchlog/runSim.$(ClusterId).log
transfer_input_files    = sandbox.tar.bz2
#getenv              = True
request_cpus        = 8


transfer_output_files = ""
+JobFlavour        = "testmatch"
queue
